---
title: "Hoarding analysis"
author: "Szymon Drobniak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
      
      code_folding: hide
      toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, tidy = TRUE)
options(digits = 2)
```

## Libraries

```{r libs message = F}

## NOTE: loading warnings suppressed
## SET YOUR WD FIRST

library(pacman)
pacman::p_load(MCMCglmm, phytools, geiger, tidyverse, ape)

library(here)

## these are installed via Biocunductor
library(ggtree)
library(ggtreeExtra)

here()
```
## Data

Loading of the data.

```{r cars}
here()
data <- read_csv(here('data', 'hoarding_data_27Jul2020.csv'))
tree <- read.tree(here('data', 'Stage2_Hackett_MCC_no_neg.tre'))
```

## MCMCglmm trials

First filter the data.

```{r}
data_analysis <- filter(data, hoarding_status != 'unknown_hoarding_status')
data_analysis <- as.data.frame(data_analysis)

names(data_analysis)[which(names(data_analysis) == 'family')] <- 'tax_family'
```

Create the basis for multinomial residual prior.

```{r}
j <- length(unique(data_analysis$hoarding_status))
IJ <- (1/j)*(diag(j-1) + matrix(1, j-1, j-1))
```

Fix the tree and generate the generalised inverse of the VCV matrix.

```{r}
tree_final$edge.length[tree_final$edge.length == 0] <- 1e-10

phylo_vcv <- inverseA(tree_final, nodes = 'ALL')
```

Run the simplest MCMCglmm model (no predictors)
```{r}
prior2 <- list(B = list(mu = rep(0, j-1), V = kronecker(IJ, 1) * (1.7 +pi^2/3)),
               R = list(V = IJ, fix = 1),
               G = list(G1 = list(V = 1, nu = 0.002, alpha.mu = 0, alpha.V = 1e4)))
model2 <- MCMCglmm(hoarding_status ~ trait - 1, 
                   random = ~tip_label,
                   rcov = ~us(trait):units,
                   prior = prior2,
                   ginverse = list(tip_label = phylo_vcv$Ainv),
                   data = data_analysis, family = 'categorical',
                   verbose = F,
                   nitt = 1e7, burnin = 1e6, thin = 5000)
```


